language: java

env:
  - DB_PROFILE=hsql
  - DB_PROFILE=h2
  - DB_PROFILE=derby

jdk:
  - oraclejdk8
  - oraclejdk7

script:
  - mvn verify -q -DcayenneTestConnection=$DB_PROFILE

# prevent Travis from uneeded "mvn install" run
install: /bin/true